### ISSUE TITLE
Put expansion button on left side on mobile version. Other websites do this as many people are holding phone with right hand and easier to extend left hand

### ISSUE THREAD

**Issue by darinpierson** [snowy-pier-games/spgbackend#2]
![image](https://user-images.githubusercontent.com/60208594/73126474-7d5b9200-3f78-11ea-983a-0a196eb340fc.png)

**Comment by kyledpierson** [comment]
Actually, it’s easier for right-handed people to reach the upper-right corner (Look at the charts on these websites):

https://ux.stackexchange.com/questions/101595/mobile-website-menu-should-hamburger-menu-be-on-left-or-the-right

https://uxplanet.org/the-ultimate-guide-to-the-hamburger-menu-and-its-alternatives-e2da8dc7f1db

However, there IS a good case for removing the hamburger menu altogether, and having the navbar be on the bottom instead.

**Comment by darinpierson** [comment]
Oh interesting. I kinda like the idea of having a navbar on the bottom. You guys want to try it?
