### ISSUE TITLE
Move "Home" to the center and change it to "Welcome to Snowy Pier Games!"

### ISSUE THREAD

**Issue by darinpierson** [snowy-pier-games/spgbackend#26]

**Comment by kyledpierson** [comment]
I'm not sure I'm on board with this one.  Are there other websites that do this?  Would it still take you to the home page?  I don't think that makes much sense from a UI perspective.  We could just get rid of the "Home" menu item altogether (since the SPG logo takes you to the home page).

**Comment by darinpierson** [comment]
I'm good closing this
