### ISSUE TITLE
The little down arrow is so far away from Games it doesn't really make sense. It also looks a little weird on mobile. Can we just delete it? It will make the header more consistent

### ISSUE THREAD

**Issue by darinpierson** [snowy-pier-games/spgbackend#32]

**Comment by kyledpierson** [comment]
Maybe we could do a hover thing like stonemaier games?

**Comment by darinpierson** [comment]
The hover thing is great - lets do it. Also, if you click the "Games" on stonemier, it takes you to the general game page. I would like that as well.
