### ISSUE TITLE
When you click "GAMES" at the top, can you have the tattered tales page underneath the link? This way it only takes one click to get to the page. Then, in the future when we have more games, when you click the links, it just moves you downwards on the games page

### ISSUE THREAD

**Issue by darinpierson** [snowy-pier-games/spgbackend#33]

**Comment by kyledpierson** [comment]
I think when we get more games we could just have a list of tiles for each game with a small blurb about the game (like how Stonemaier does it), and then you can click on those tiles take you to a full page about the game.  So I can add a tile for Tattered Tales.

**Comment by darinpierson** [comment]
Yeah we can do that.
