### ISSUE TITLE
For Mobile - on the Contact Us page, can you put some more white space underneath the "submit" button?

### ISSUE THREAD

**Issue by darinpierson** [snowy-pier-games/spgbackend#74]

**Comment by kyledpierson** [comment]
Can you show me a screenshot of what you have and sketch out how much you want?

**Comment by darinpierson** [comment]
![image](https://user-images.githubusercontent.com/60208594/82731692-49963c00-9cce-11ea-999b-7b953d562239.png)

**Comment by darinpierson** [comment]
Not too picky - doesn't need to be exact

**Comment by kyledpierson** [comment]
Weird, there definitely used to be a gap there
