### ISSUE TITLE
For Mobile - on the subscribe page, can you put more white space underneath the "Submit" button?

### ISSUE THREAD

**Issue by darinpierson** [snowy-pier-games/spgbackend#75]

**Comment by kyledpierson** [comment]
Can you show me a screenshot of what you have and sketch out how much you want?

**Comment by darinpierson** [comment]
Similar space to the contact us. Just the same amount of whitespace that is above the button
![image](https://user-images.githubusercontent.com/60208594/82731719-6d598200-9cce-11ea-8159-6b9b24c2a187.png)
